services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: bankmanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  discoverydocker:
    build: ./banking-discoveryService
    container_name: discoverydocker
    ports: 
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8761/actuator/health"]
      interval: 10s
  configdocker:
    build: ./banking-configService
    container_name: configdocker
    ports: 
      - '8888:8888'
    expose:
      - '8888'  
    environment:
      - DISCOVERY_URL=http://discoverydocker:8761/eureka  
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8888/actuator/health"]
      interval: 10s 
    depends_on:
      discoverydocker:
        condition: service_healthy
  transactiondocker:
    build: ./transactionBakingSystem
    container_name: transactiondocker
    ports:
      - '8081:8081'
    expose:
      - '8081'   
    environment:
      - DISCOVERY_URL=http://discoverydocker:8761/eureka 
      - CONFIG_URL=http://configdocker:8888  
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bankmanagement
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin       
    depends_on:
      configdocker:
        condition: service_healthy
  gatwaydocker:
    build: ./gatWayService
    container_name: gatwaydocker
    ports:
      - '8080:8080'
    expose:
      - '8080'   
    environment:
      - DISCOVERY_URL=http://discoverydocker:8761/eureka 
      - CONFIG_URL=http://configdocker:8888   
    depends_on:
      configdocker:
        condition: service_healthy









